version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
        volumes:
            -   .:/var/www/html
        networks:
            - laravel-chat
        depends_on:
            -  mysql


    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   mysql
            - app
        networks:
            - laravel-chat

    mysql:
        image: mysql:8.0
        container_name: ${APP_NAME}-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        volumes:
            -   ./docker/mysql:/var/lib/mysql
        networks:
            - laravel-chat

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - laravel-chat

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"
        networks:
            - laravel-chat
        depends_on:
            -   mysql

networks:
    laravel-chat:
